{% set name = "lazrs-python" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/lazrs/lazrs-{{ version }}.tar.gz
  sha256: 223ea747140ef374c9cac9cb226aa0fc5bb25988fc2138a24d4152ba819dd38e

build:
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [ppc64le and python_impl == 'pypy']

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=1.0.0,<2.0.0
    - python                                 # [build_platform != target_platform]
  host:
    - maturin >=1.0.0,<2.0.0
    - pip
    - python
  run:
    - python

test:
  imports:
    - lazrs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/lazrs/
  summary: Python bindings for laz-rs
  license: MIT
  license_file:
    - THIRDPARTY.yml
    - LICENSE.txt
  dev_url: https://github.com/laz-rs/laz-rs-python

extra:
  recipe-maintainers:
    - hobu
    - tmontaigu
    - weiji14
