{% set name = "lazrs-python" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/lazrs/lazrs-{{ version }}.tar.gz
  sha256: 793359e94eb436b34877b4305570774f9b1bba34c4671238512b80b60456d9ce

build:
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv
  number: 1
  skip: true  # [py<39]
  skip: true  # [ppc64le and python_impl == 'pypy']

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=0.14,<0.15
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - maturin >=0.14,<0.15
    - python
    - pip
  run:
    - python

test:
  imports:
    - lazrs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/lazrs/
  summary: Python bindings for laz-rs
  license: MIT
  license_file:
    - THIRDPARTY.yml
    - LICENSE.txt
  dev_url: https://github.com/laz-rs/laz-rs-python

extra:
  recipe-maintainers:
    - hobu
    - tmontaigu
    - weiji14
